"""
AI Handler
Handles AI-powered features like summaries and quizzes.
"""
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes
import sys
sys.path.append('../..')
from database.models import get_session, Theme, Book
from services.ai_summary import generate_summary, generate_quiz


async def handle_summary_request(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle AI Summary button click."""
    query = update.callback_query
    await query.answer("Generating AI summary... Please wait ⏳")
    
    callback_data = query.data
    if not callback_data.startswith('summary_'):
        return
    
    theme_id = int(callback_data.replace('summary_', ''))
    
    # Get theme from database
    session = get_session()
    theme = session.query(Theme).filter(Theme.id == theme_id).first()
    
    if not theme:
        await query.message.reply_text("❌ Theme not found.")
        return
    
    book = session.query(Book).filter(Book.id == theme.book_id).first()
    
    # Determine content and language
    content = theme.content_uz or theme.content_ru or ""
    name = theme.name_uz or theme.name_ru or "Theme"
    language = 'uz' if theme.content_uz else 'ru'
    
    if not content or len(content) < 100:
        await query.message.reply_text(
            "❌ Not enough content to generate summary.\n"
            "This chapter doesn't have extracted text."
        )
        return
    
    # Generate summary
    try:
        summary = generate_summary(content, name, language)
        
        if summary:
            response = (
                f"📝 AI Summary\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"📖 {name}\n"
                f"📚 {book.title_uz or book.title_ru if book else 'Unknown'}\n"
                f"━━━━━━━━━━━━━━━━━━\n\n"
                f"{summary}\n\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"🤖 Generated by AI"
            )
            
            # Add buttons: Refresh and Back
            keyboard = [
                [InlineKeyboardButton("🔄 Refresh Summary", callback_data=f"summary_{theme_id}")],
                [InlineKeyboardButton("🔙 Back to Theme", callback_data=f"theme_{theme_id}")]
            ]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            await query.message.reply_text(
                response,
                reply_markup=reply_markup
            )
        else:
            await query.message.reply_text(
                "❌ Failed to generate summary.\n"
                "Please check that GROQ_API_KEY is set in .env file."
            )
    except Exception as e:
        await query.message.reply_text(f"❌ Error: {str(e)}")


async def handle_quiz_request(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle AI Quiz button click."""
    query = update.callback_query
    await query.answer("Generating 10 quiz questions... Please wait ⏳")
    
    callback_data = query.data
    if not callback_data.startswith('quiz_'):
        return
    
    theme_id = int(callback_data.replace('quiz_', ''))
    
    # Get theme from database
    session = get_session()
    theme = session.query(Theme).filter(Theme.id == theme_id).first()
    
    if not theme:
        await query.message.reply_text("❌ Theme not found.")
        return
    
    book = session.query(Book).filter(Book.id == theme.book_id).first()
    
    # Determine content and language
    content = theme.content_uz or theme.content_ru or ""
    name = theme.name_uz or theme.name_ru or "Theme"
    language = 'uz' if theme.content_uz else 'ru'
    
    if not content or len(content) < 100:
        await query.message.reply_text(
            "❌ Not enough content to generate quiz.\n"
            "This chapter doesn't have extracted text."
        )
        return
    
    # Generate quiz with 5 questions (shorter to fit Telegram limit)
    try:
        quiz = generate_quiz(content, name, num_questions=5, language=language)
        
        if quiz:
            # Escape HTML special characters (except our spoiler tags)
            import html
            def escape_html_keep_spoilers(text):
                # First escape all HTML
                escaped = html.escape(text)
                # Then restore our spoiler tags
                escaped = escaped.replace('&lt;tg-spoiler&gt;', '<tg-spoiler>')
                escaped = escaped.replace('&lt;/tg-spoiler&gt;', '</tg-spoiler>')
                return escaped
            
            book_title = book.title_uz or book.title_ru if book else 'Unknown'
            
            safe_name = html.escape(name)
            safe_book_title = html.escape(book_title)
            safe_quiz = escape_html_keep_spoilers(quiz)
            
            response = (
                f"📋 AI Quiz - 5 Questions\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"📖 {safe_name}\n"
                f"📚 {safe_book_title}\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"Tap spoiler to reveal answer\n\n"
                f"{safe_quiz}\n\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"🤖 Generated by AI"
            )
            
            # Telegram limit is 4096, split if needed
            if len(response) > 4000:
                response = (
                    f"📋 AI Quiz\n"
                    f"📖 {safe_name[:30]}\n\n"
                    f"{safe_quiz[:3500]}"
                )
            
            # Add buttons: Refresh and Back
            keyboard = [
                [InlineKeyboardButton("🔄 Refresh Quiz", callback_data=f"quiz_{theme_id}")],
                [InlineKeyboardButton("🔙 Back to Theme", callback_data=f"theme_{theme_id}")]
            ]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            await query.message.reply_text(
                response,
                reply_markup=reply_markup,
                parse_mode='HTML'
            )
        else:
            await query.message.reply_text(
                "❌ Failed to generate quiz.\n"
                "Please check that GROQ_API_KEY is set in .env file."
            )
    except Exception as e:
        print(f"Quiz error: {e}")
        await query.message.reply_text(f"❌ Error: {str(e)}")
